Repository woorifisa-projects-3rd/WithBeeTravel-FE, pull requests merged in 2024-11, with the labels that each got.

#11 [Feat/TK-32 travelselect] : 여행 선택하기 퍼블리싱
  apps/mobile/app/travel/select/page.module.css
  apps/mobile/app/travel/select/page.tsx
  apps/mobile/public/friends/1.png
  apps/mobile/public/friends/10.png
  apps/mobile/public/friends/2.png
  apps/mobile/public/friends/3.png
  apps/mobile/public/friends/4.png
  apps/mobile/public/friends/5.png
  apps/mobile/public/friends/6.png
  apps/mobile/public/friends/7.png
  apps/mobile/public/friends/8.png
  apps/mobile/public/friends/9.png
  apps/mobile/public/friends/wibee_gray.png
  apps/mobile/public/imgs/travel/airplane.png
  apps/mobile/public/imgs/travel/travel_exam.png
  apps/mobile/public/imgs/travel/travel_select_invitecode.png
  apps/mobile/public/imgs/travel/travel_select_plane.png
  apps/mobile/public/imgs/travel/withbee_friends.png
  apps/mobile/public/imgs/travel/withbee_friends_background.png
  apps/storybook/stories/Modal.stories.tsx
  packages/ui/src/modal.module.css
  packages/ui/src/modal.tsx
  packages/ui/src/title.module.css
Labels: ✨ feature

#27 chore: 프리티어 CI
  .github/workflows/prettier-auto-fix.yml
Labels: 👷ci

#26 [Feat/tk 104 footer]-하단 메뉴 퍼블리싱
  apps/mobile/app/banking/page.tsx
  apps/mobile/app/global.css
  apps/mobile/app/layout.tsx
  apps/mobile/app/travel/[id]/page.module.css
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/app/travel/select/page.module.css
  apps/mobile/app/travel/select/page.tsx
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/components/MobileFooter.tsx
  packages/ui/src/modal.module.css
  packages/ui/src/modal.tsx
Labels: ✨ feature

#17 [Feat/TK-75]: 지출 상세 내역 퍼블리싱
  apps/mobile/app/banking/page.tsx
  apps/mobile/app/global.css
  apps/mobile/app/layout.tsx
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/MobileFooter.tsx
  apps/mobile/public/arrow.png
  apps/storybook/stories/Modal.stories.tsx
  packages/ui/src/modal.module.css
  packages/ui/src/modal.tsx
  pnpm-lock.yaml
Labels: ✨ feature

#24 Feat/tk 121 shared payments publishing
  apps/mobile/app/global.css
  apps/mobile/app/travel/[id]/page.module.css
  apps/mobile/app/travel/[id]/payments/page.module.css
  apps/mobile/app/travel/[id]/payments/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/public/arrow-right.png
  apps/mobile/public/imgs/travel/wibee_gray.png
  apps/mobile/public/setting.png
  packages/styles/global.css
  packages/ui/package.json
  packages/ui/src/friend-image.module.css
  packages/ui/src/friend-image.tsx
  packages/ui/src/payment.module.css
  packages/ui/src/payment.tsx
  packages/ui/src/tab-group.module.css
  packages/ui/src/tab-group.tsx
  packages/ui/src/tag.module.css
  packages/ui/src/tag.tsx
  packages/ui/src/title.module.css
  packages/ui/src/title.tsx
Labels: ✨ feature

#32 [Feat/TK-124] 여행 생성하기 페이지
  apps/mobile/app/global.css
  apps/mobile/app/layout.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/form/page.module.css
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/MobileFooter.tsx
  apps/mobile/components/TravelForm.module.css
  apps/mobile/components/TravelForm.tsx
  apps/mobile/public/Airplane.ico
  apps/mobile/public/imgs/travel/airplane.png
  apps/mobile/public/imgs/travelform/Search.png
  apps/mobile/public/imgs/travelselect/travel_exam.png
  apps/mobile/public/imgs/travelselect/travel_select_invitecode.png
  apps/mobile/public/imgs/travelselect/travel_select_plane.png
  apps/mobile/public/imgs/travelselect/wibee_gray.png
  apps/mobile/public/imgs/travelselect/withbee_friends.png
  apps/mobile/public/imgs/travelselect/withbee_friends_background.png
  packages/styles/global.css
  packages/ui/src/button.module.css
  packages/ui/src/button.tsx
  packages/ui/src/modal.module.css
  packages/ui/src/modal.tsx
Labels: ✨ feature

#25 [Feat/TK-122] 정산 동의 페이지 퍼블리싱
  apps/mobile/app/travel/[id]/agreement/completed/page.module.css
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/agreement/page.module.css
  apps/mobile/app/travel/[id]/agreement/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/package.json
  apps/mobile/public/agreeOpen.png
  apps/mobile/public/check.png
  apps/mobile/public/friends/agreeWibee.png
  apps/mobile/public/uncheck.png
  packages/ui/src/title.module.css
  packages/utils/consentItems.js
  pnpm-lock.yaml
Labels: ✨ feature

#37 [Feat/TK-129] api setting
  apps/mobile/app/page.tsx
  apps/mobile/package.json
  packages/apis/.eslintrc.js
  packages/apis/package.json
  packages/apis/src/index.ts
  packages/apis/src/instance.ts
  packages/apis/src/sharedPaymentsService.ts
  packages/apis/tsconfig.json
  packages/apis/tsconfig.lint.json
  pnpm-lock.yaml
Labels: ✨ feature

#41 [Feat/TK-129] API instance 관련 타입 에러 해결
  apps/mobile/app/page.tsx
  packages/apis/src/instance.ts
Labels: 🐞bug

#38 style: 프리티어 재설정
  .prettierrc.js
  .vscode/settings.json
  package.json
  packages/eslint-config/next.js
  packages/prettier-config/index.js
  packages/prettier-config/package.json
  pnpm-lock.yaml
Labels: ♻️ refactor

#39 [Feat/TK-121] 공동지출내역 모달
  apps/mobile/app/travel/[id]/page.module.css
  apps/mobile/package.json
  apps/mobile/public/imgs/friends/1.png
  apps/mobile/public/imgs/friends/10.png
  apps/mobile/public/imgs/friends/2.png
  apps/mobile/public/imgs/friends/3.png
  apps/mobile/public/imgs/friends/4.png
  apps/mobile/public/imgs/friends/5.png
  apps/mobile/public/imgs/friends/6.png
  apps/mobile/public/imgs/friends/7.png
  apps/mobile/public/imgs/friends/8.png
  apps/mobile/public/imgs/friends/9.png
  apps/mobile/public/imgs/friends/agreeWibee.png
  apps/storybook/stories/DatePicker.stories.tsx
  packages/stores/src/index.ts
  packages/styles/global.css
  packages/ui/package.json
  packages/ui/src/assets/arrow_right.png
  packages/ui/src/assets/not_select.png
  packages/ui/src/assets/select.png
  packages/ui/src/button.tsx
  packages/ui/src/date-picker-modal.module.css
  packages/ui/src/date-picker-modal.tsx
  packages/ui/src/friend-image.tsx
  packages/ui/src/menu.module.css
  packages/ui/src/menu.tsx
  packages/ui/src/modal.module.css
  packages/ui/src/modal.tsx
  packages/ui/src/payment.module.css
  packages/ui/src/payment.tsx
  packages/ui/src/tag.tsx
  pnpm-lock.yaml
Labels: ✨ feature

#34 [Feat/tk 124]-여행 컴포넌트 퍼블리싱 수정
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/[id]/payments/page.tsx
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/TravelForm.module.css
  apps/mobile/components/TravelForm.tsx
  apps/mobile/package.json
  apps/mobile/public/imgs/travelform/Search.png
  apps/mobile/public/imgs/travelform/cal.png
  packages/apis/src/index.ts
  packages/apis/src/instance.ts
  packages/apis/src/travelService.ts
  packages/hooks/.eslintrc.js
  packages/hooks/package.json
  packages/hooks/src/useToast.ts
  packages/hooks/tsconfig.json
  packages/hooks/tsconfig.lint.json
  packages/ui/package.json
  packages/ui/src/assets/title/bell.png
  packages/ui/src/button.tsx
  packages/ui/src/card.tsx
  packages/ui/src/date-picker-modal.module.css
  packages/ui/src/item-group.module.css
  packages/ui/src/item-group.tsx
  packages/ui/src/item.module.css
  packages/ui/src/item.tsx
  packages/ui/src/menu.tsx
  packages/ui/src/modal.module.css
  packages/ui/src/payment.tsx
  packages/ui/src/title.tsx
  packages/ui/src/toast-container.module.css
  packages/ui/src/toast-container.tsx
  packages/utils/dateUtils.ts
  packages/utils/validCheck.ts
  pnpm-lock.yaml
Labels: ✨ feature

#54 [Feat/TK-161] ci
  .github/workflows/quality-checks.yml
  apps/admin/app/page.tsx
  apps/admin/package.json
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/agreement/page.tsx
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/custom.d.ts
  apps/mobile/package.json
  apps/mobile/tsconfig.json
  apps/pc/app/page.tsx
  apps/pc/package.json
  apps/storybook/app/page.tsx
  apps/storybook/custom.d.ts
  apps/storybook/package.json
  apps/storybook/stories/Header.stories.ts
  apps/storybook/stories/Title.stories.tsx
  apps/storybook/tsconfig.json
  package.json
  packages/apis/.eslintrc.js
  packages/apis/package.json
  packages/exception/.eslintrc.js
  packages/exception/package.json
  packages/hooks/.eslintrc.js
  packages/hooks/package.json
  packages/stores/.eslintrc.js
  packages/stores/package.json
  packages/stores/src/index.ts
  packages/styles/global.css
  packages/ui/.eslintrc.js
  packages/ui/custom.d.ts
  packages/ui/package.json
  packages/ui/src/button.tsx
  packages/ui/src/date-picker-modal.module.css
  packages/ui/tsconfig.json
  packages/ui/tsconfig.lint.json
  turbo.json
Labels: 👷ci

#52 [fix/TK-124]:dateObject utils로 빼기
  apps/mobile/app/travel/page.module.css
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/components/TravelForm.module.css
  apps/mobile/components/TravelForm.tsx
  packages/styles/global.css
  packages/ui/src/date-picker-modal.module.css
  packages/ui/src/toast-container.tsx
  packages/utils/dateUtils.ts
Labels: ♻️ refactor

#48 [Feat/TK-137] 지출상세내역 API 연동
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/components/ExpenseDetails.tsx
  apps/mobile/components/ModalWrapper.tsx
  apps/mobile/package.json
  apps/mobile/public/imgs/settlement/stamp.png
  apps/storybook/package.json
  packages/apis/src/index.ts
  packages/apis/src/settlementService.ts
  pnpm-lock.yaml
Labels: ✨ feature

#46 Feat/tk 125 보유계좌 목록 페이지 구현
  .gitignore
  apps/mobile/app/banking/[id]/deposit/page.module.css
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/page.module.css
  apps/mobile/app/banking/[id]/page.tsx
  apps/mobile/app/banking/[id]/payment/page.module.css
  apps/mobile/app/banking/[id]/payment/page.tsx
  apps/mobile/app/banking/[id]/transfer/detail/page.module.css
  apps/mobile/app/banking/[id]/transfer/detail/page.tsx
  apps/mobile/app/banking/[id]/transfer/page.module.css
  apps/mobile/app/banking/[id]/transfer/page.tsx
  apps/mobile/app/banking/create/page.module.css
  apps/mobile/app/banking/create/page.tsx
  apps/mobile/app/banking/page.module.css
  apps/mobile/app/banking/page.tsx
  package.json
  packages/ui/src/button.module.css
  packages/ui/src/button.tsx
  pnpm-lock.yaml
  stories/Button.tsx
Labels: ✨ feature

#64 [feat/TK-153]: ErrorBoundary, Suspense로 에러 및 로딩 상태 처리
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/[id]/payments/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/app/travel/form/page.tsx
  packages/apis/src/index.ts
  packages/exception/src/CustomException.ts
  packages/ui/package.json
  packages/ui/src/payment-error-boundary.tsx
  packages/ui/src/payment-list.tsx
  packages/ui/src/payment-skeleton.module.css
  packages/ui/src/payment-skeleton.tsx
Labels: ♻️ refactor

#58 [fix/TK-124]:modal 제출 버튼, 닫기 버튼 분리
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.tsx
  packages/apis/src/travelService.ts
  packages/ui/src/modal.tsx
Labels: 🐞bug

#65 [fix/TK-124]:TYPE 분리
  packages/apis/src/travelService.ts
  packages/types/src/index.ts
  packages/types/src/travelService.ts
Labels: ✨ feature

#35 [Feat/TK-126] 알림창 퍼블리싱
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/public/notifications/arrow.png
  packages/ui/src/title.tsx
  packages/utils/src/dateUtils.ts
  pnpm-lock.yaml
Labels: ✨ feature

#67 [fix/TK-124]:퍼블리싱 수정
  apps/mobile/app/travel/page.module.css
  apps/mobile/components/TravelForm.module.css
  apps/mobile/public/imgs/travelselect/travel_select_invitecode.png
  apps/mobile/public/imgs/travelselect/travel_select_plane.png
Labels: ♻️ refactor

#47 [Feat/tk 140]-여행 편집 API 연동
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/components/TravelForm.tsx
  packages/apis/src/index.ts
  packages/apis/src/travelService.ts
Labels: ✨ feature

#80 [feat/TK-192]: 네비 숨길 url 추가
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/components/MobileFooter.tsx
  packages/apis/src/index.ts
Labels: ✨ feature

#77 Feat/tk 167 핀번호 화면 구현
  apps/mobile/app/banking/[id]/deposit/page.module.css
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/page.module.css
  apps/mobile/app/banking/[id]/page.tsx
  apps/mobile/app/banking/[id]/payment/page.module.css
  apps/mobile/app/banking/[id]/payment/page.tsx
  apps/mobile/app/banking/[id]/transfer/detail/page.module.css
  apps/mobile/app/banking/[id]/transfer/detail/page.tsx
  apps/mobile/app/banking/[id]/transfer/page.module.css
  apps/mobile/app/banking/[id]/transfer/page.tsx
  apps/mobile/app/banking/create/page.module.css
  apps/mobile/app/banking/create/page.tsx
  apps/mobile/app/banking/page.module.css
  apps/mobile/app/banking/page.tsx
  apps/mobile/components/PinNumberModal.module.css
  apps/mobile/components/PinNumberModal.tsx
  packages/hooks/src/useToast.ts
Labels: ✨ feature

#75 Feat/tk 179 초대 코드 api 연동
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/InviteCodeModal.module.css
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/package.json
  apps/mobile/public/copy.png
  apps/mobile/public/imgs/travelselect/travel_select_invitecode.png
  apps/mobile/public/imgs/travelselect/travel_select_plane.png
  packages/apis/src/index.ts
  packages/apis/src/inviteCode.ts
  packages/apis/src/travelService.ts
  packages/types/src/travelService.ts
  pnpm-lock.yaml
Labels: ✨ feature

#71 [Feat/TK-181] 정산 동의 API 연동
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/agreement/page.tsx
  apps/mobile/app/travel/[id]/agreement/pending/page.module.css
  apps/mobile/app/travel/[id]/agreement/pending/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/public/imgs/agreement/angryWibee.png
  packages/apis/src/index.ts
  packages/apis/src/notificationService.ts
  packages/apis/src/settlementService.ts
Labels: ✨ feature

#72 [Feat/TK-153] 공동지출내역 API 연동, 에러 처리
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/travel/[id]/agreement/page.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/[id]/payments/error.tsx
  apps/mobile/app/travel/[id]/payments/layout.tsx
  apps/mobile/app/travel/[id]/payments/loading.tsx
  apps/mobile/app/travel/[id]/payments/page.module.css
  apps/mobile/app/travel/[id]/payments/page.tsx
  apps/mobile/components/MobileFooter.tsx
  apps/mobile/public/imgs/friends/notfound.png
  packages/apis/src/instance.ts
  packages/apis/src/sharedPaymentsService.ts
  packages/apis/src/travelService.ts
  packages/exception/src/CustomException.ts
  packages/hooks/src/useToast.ts
  packages/stores/package.json
  packages/stores/src/index.ts
  packages/stores/src/travelPaymentsStore.ts
  packages/stores/src/travelStore.tsx
  packages/types/src/index.ts
  packages/types/src/sharedPaymentsType.ts
  packages/types/src/travelType.ts
  packages/ui/src/button.module.css
  packages/ui/src/button.tsx
  packages/ui/src/friend-image.tsx
  packages/ui/src/item-group.tsx
  packages/ui/src/menu.module.css
  packages/ui/src/menu.tsx
  packages/ui/src/payment-error-boundary.tsx
  packages/ui/src/payment-list.module.css
  packages/ui/src/payment-list.tsx
  packages/ui/src/payment-skeleton.tsx
  packages/ui/src/payment.tsx
  packages/ui/src/toast-container.tsx
  pnpm-lock.yaml
Labels: ♻️ refactor, ✨ feature

#69 [Feat/TK-177] 정산 취소 API 연동 및 지출 세부 내역 퍼블리싱 수정
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/travel/[id]/agreement/pending/page.tsx
  apps/mobile/app/travel/[id]/settlement/canceled/page.module.css
  apps/mobile/app/travel/[id]/settlement/canceled/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/components/ExpenseDetails.tsx
  apps/mobile/components/ModalWrapper.tsx
  apps/mobile/public/imgs/settlement/cancelWibee.png
  packages/apis/src/settlementService.ts
Labels: ✨ feature

#84 [Feat/TK-194 ]카드 혜택 페이지 구현
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/[id]/invite-code-button.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/components/MobileFooter.tsx
  apps/mobile/public/imgs/cardBenefits/1.png
  apps/mobile/public/imgs/cardBenefits/2.png
  apps/mobile/public/imgs/cardBenefits/3.png
  apps/mobile/public/imgs/cardBenefits/withbee_checkcard.png
  apps/mobile/public/imgs/cardBenefits/withbee_travel_checkcard.png
  apps/mobile/public/imgs/travelselect/travel_base_mainImage.png
  apps/mobile/public/imgs/travelselect/withbee_friends_background.png
  packages/apis/src/travelService.ts
  packages/types/src/travelService.ts
  packages/ui/src/friend-image.tsx
  packages/ui/src/modal.tsx
Labels: ✨ feature

#74 [feat/TK-186]: 여행 홈 GET API 연동
  apps/mobile/app/travel/[id]/page.module.css
  apps/mobile/app/travel/[id]/page.tsx
  packages/apis/src/sharedPaymentsService.ts
  packages/apis/src/travelService.ts
  packages/types/src/travelType.ts
  packages/ui/src/chart.tsx
  packages/utils/package.json
  packages/utils/src/dateUtils.ts
  pnpm-lock.yaml
Labels: ✨ feature

#98 [Feat/TK-177]: 세부 지출 내역 api 필드 수정
  apps/mobile/app/travel/[id]/settlement/page.tsx
  packages/apis/src/settlementService.ts
Labels: 🐞bug

#97 Feat/tk 198 뱅킹 api 요청 방식 수정
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/page.tsx
  apps/mobile/app/banking/[id]/payment/page.tsx
  apps/mobile/app/banking/[id]/transfer/detail/page.tsx
  apps/mobile/app/banking/[id]/transfer/page.tsx
  apps/mobile/app/banking/create/page.tsx
  apps/mobile/app/banking/page.tsx
  apps/mobile/components/PinNumberModal.tsx
  packages/apis/src/bankingService.ts
  packages/apis/src/index.ts
  packages/types/src/bankingType.ts
  packages/types/src/index.ts
Labels: ♻️ refactor

#103 [feat/TK-165]: 직접 결제 내역 추가 페이지에 통화 코드 목록을 방문 국가의 통화 코드가 우선 뜨도록 구현
  apps/mobile/app/travel/[id]/manual/page.tsx
  apps/mobile/app/travel/[id]/payments/layout.tsx
  packages/apis/src/createManualSharedPayment.ts
  packages/types/src/index.ts
  packages/types/src/manualSharedPayment.ts
  packages/ui/src/menu.tsx
Labels: ♻️ refactor, ✨ feature

#104 [Feat/tk - 212] - 코드 리팩토링
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/[id]/form/page.module.css
  apps/mobile/app/travel/[id]/form/page.tsx
  apps/mobile/app/travel/[id]/invite-code-button.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/form/page.module.css
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/components/TravelForm.tsx
  apps/mobile/next.config.mjs
  apps/mobile/public/imgs/cardBenefits/background.png
  apps/mobile/public/imgs/travelselect/emptyStateTrip.png
  packages/apis/src/bankingService.ts
  packages/apis/src/travelService.ts
  packages/hooks/src/useToast.ts
  packages/types/src/bankingType.ts
  packages/utils/src/consentItems.ts
Labels: ♻️ refactor

#115 Feat/tk 212 코드 리팩토링
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
Labels: ✨ feature

#106 [Feat/TK-153] 공동지출내역 리팩토링
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/[id]/payments/error.tsx
  apps/mobile/app/travel/[id]/payments/layout.tsx
  apps/mobile/app/travel/[id]/payments/page.module.css
  apps/mobile/app/travel/[id]/payments/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/components/ModalWrapper.tsx
  packages/apis/src/settlementService.ts
  packages/apis/src/sharedPaymentsService.ts
  packages/apis/src/travelService.ts
  packages/hooks/package.json
  packages/hooks/src/usePaymentParams.ts
  packages/types/src/sharedPaymentsType.ts
  packages/types/src/travelType.ts
  packages/ui/package.json
  packages/ui/src/animated-button.module.css
  packages/ui/src/animated-button.tsx
  packages/ui/src/button.tsx
  packages/ui/src/item-group.tsx
  packages/ui/src/menu.tsx
  packages/ui/src/payment-error-boundary.tsx
  packages/ui/src/payment-error.module.css
  packages/ui/src/payment-error.tsx
  packages/ui/src/payment-list.module.css
  packages/ui/src/payment-list.tsx
  packages/ui/src/payment.module.css
  packages/ui/src/payment.tsx
  packages/ui/src/settlement-button.module.css
  packages/ui/src/settlement-button.tsx
  pnpm-lock.yaml
Labels: ♻️ refactor

#118 Feat/tk 231 뱅킹 홈 디테일 수정
  apps/mobile/app/banking/[id]/deposit/page.module.css
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/page.tsx
  apps/mobile/app/banking/[id]/transfer/page.tsx
  apps/mobile/app/banking/page.tsx
  apps/mobile/components/TotalBalanceCountUp.module.css
  apps/mobile/components/TotalBalanceCountUp.tsx
  apps/mobile/package.json
  packages/utils/src/index.ts
  packages/utils/src/numberToKorean.ts
  pnpm-lock.yaml
Labels: ♻️ refactor
