Repository woorifisa-projects-3rd/WithBeeTravel-FE, pull requests merged in 2024-12, with the labels that each got.

#119 [Feat/TK-204] 로그인/회원가입
  apps/mobile/app/(auth)/join/page.module.css
  apps/mobile/app/(auth)/join/page.tsx
  apps/mobile/app/(auth)/login/page.module.css
  apps/mobile/app/(auth)/login/page.tsx
  apps/mobile/app/(auth)/page.module.css
  apps/mobile/app/actions/authActions.ts
  apps/mobile/app/banking/[id]/page.tsx
  apps/mobile/components/AuthForm.module.css
  apps/mobile/components/JoinForm.tsx
  apps/mobile/components/LoginForm.tsx
  apps/mobile/components/PinNumberModal.module.css
  apps/mobile/components/PinNumberModal.tsx
  apps/mobile/middleware.ts
  apps/mobile/next-auth.d.ts
  apps/mobile/package.json
  apps/mobile/public/back.png
  packages/apis/src/authService.ts
  packages/apis/src/instance.ts
  packages/auth-config/src/auth.ts
  packages/auth-config/src/instance.ts
  packages/auth-config/types/next-auth.d.ts
  packages/types/src/authType.ts
  packages/ui/src/button.module.css
  packages/ui/src/payment-list.module.css
  packages/ui/src/payment-list.tsx
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/validation/index.ts
  packages/utils/src/validation/joinSchema.ts
  packages/utils/src/validation/validateJoinForm.ts
  pnpm-lock.yaml
Labels: ♻️ refactor, ✨ feature

#120 Feat/tk 212 코드 리팩토링
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/[id]/form/page.module.css
  apps/mobile/app/travel/[id]/form/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/InviteCodeModal.module.css
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/components/TravelForm.tsx
  apps/mobile/public/copy.png
  apps/mobile/public/imgs/travelform/share.png
  apps/pc/app/(auth)/join/page.module.css
  apps/pc/app/(auth)/join/page.tsx
  apps/pc/app/(auth)/login/page.module.css
  apps/pc/app/(auth)/login/page.tsx
  apps/pc/app/actions/authActions.ts
  apps/pc/app/api/auth/[...nextauth]/route.ts
  apps/pc/app/banking/[id]/deposit/page.module.css
  apps/pc/app/banking/[id]/deposit/page.tsx
  apps/pc/app/banking/[id]/page.module.css
  apps/pc/app/banking/[id]/page.tsx
  apps/pc/app/banking/[id]/payment/page.module.css
  apps/pc/app/banking/[id]/payment/page.tsx
  apps/pc/app/banking/[id]/transfer/detail/page.module.css
  apps/pc/app/banking/[id]/transfer/detail/page.tsx
  apps/pc/app/banking/[id]/transfer/page.module.css
  apps/pc/app/banking/[id]/transfer/page.tsx
  apps/pc/app/banking/create/page.module.css
  apps/pc/app/banking/create/page.tsx
  apps/pc/app/banking/page.module.css
  apps/pc/app/banking/page.tsx
  apps/pc/app/favicon.ico
  apps/pc/app/mypage/page.module.css
  apps/pc/app/mypage/page.tsx
  apps/pc/app/notification/page.module.css
  apps/pc/app/notification/page.tsx
  packages/apis/src/travelService.ts
  packages/types/src/Kakao.ts
  packages/types/src/index.ts
  packages/types/src/travelService.ts
  packages/types/src/travelType.ts
Labels: ♻️ refactor, ✨ feature

#99 Feat/tk 193 위비 카드 결제 내역 불러오기 페이지 구현
  apps/mobile/app/travel/[id]/manual/page.tsx
  apps/mobile/app/travel/[id]/wibee-card/page.module.css
  apps/mobile/app/travel/[id]/wibee-card/page.tsx
  apps/mobile/public/arrow_right.png
  apps/pc/auth.ts
  apps/pc/components/AccountSelection.module.css
  apps/pc/components/AccountSelection.tsx
  apps/pc/components/PinNumberModal.module copy.css
  apps/pc/components/PinNumberModal.module.css
  apps/pc/components/PinNumberModal.tsx
  apps/pc/components/TotalBalanceCountUp.module.css
  apps/pc/components/TotalBalanceCountUp.tsx
  apps/pc/custom.d.ts
  apps/pc/package.json
  apps/pc/tsconfig.json
  packages/apis/src/createManualSharedPayment.ts
  packages/apis/src/getCurrencyDate.ts
  packages/apis/src/index.ts
  packages/apis/src/wibeeCardHistory.ts
  packages/types/src/index.ts
  packages/types/src/wibeeCardHistoryType.ts
  packages/ui/package.json
  packages/ui/src/manual-shared-payment-form.tsx
  packages/ui/src/menu.tsx
  packages/ui/src/wibee-card-payment.module.css
  packages/ui/src/wibee-card-payment.tsx
  packages/utils/src/validCheck.ts
  pnpm-lock.yaml
Labels: ✨ feature

#107 Feat/tk 218 공동 결제 내역 기록 모달 구현
  apps/mobile/app/travel/[id]/page.module.css
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/page.tsx
  packages/apis/src/sharedPaymentsService.ts
  packages/types/src/sharedPaymentsType.ts
  packages/ui/package.json
  packages/ui/src/manual-shared-payment-form.module.css
  packages/ui/src/payment.tsx
  packages/ui/src/record-image.module.css
  packages/ui/src/record-image.tsx
  packages/ui/src/record-modal.module.css
  packages/ui/src/record-modal.tsx
Labels: ✨ feature

#112 Feat/tk 221 허니 캡슐
  apps/mobile/app/travel/[id]/honey-capsule/page.module.css
  apps/mobile/app/travel/[id]/honey-capsule/page.tsx
  apps/mobile/app/travel/[id]/page.tsx
  packages/apis/src/honeyCapsuleService.ts
  packages/apis/src/index.ts
  packages/types/src/honeyCapsuleType.ts
  packages/types/src/index.ts
  packages/ui/package.json
  packages/ui/src/honey-capsule.module.css
  packages/ui/src/honey-capsule.tsx
Labels: ✨ feature

#114 Feat/tk 227 허니캡슐 이미지로 다운
  apps/mobile/app/travel/[id]/honey-capsule/page.tsx
  apps/mobile/package.json
  pnpm-lock.yaml
Labels: ✨ feature

#127 [refactor/TK-231]: 계좌 생성, notFound 스타일 수정
  apps/mobile/app/banking/[id]/page.module.css
  apps/mobile/app/banking/create/page.module.css
  apps/mobile/app/banking/create/page.tsx
  apps/mobile/app/banking/page.module.css
  apps/mobile/app/banking/page.tsx
  apps/mobile/app/not-found.module.css
  apps/mobile/app/not-found.tsx
  apps/mobile/app/page.module.css
  apps/mobile/components/AccountSelection.module.css
  apps/mobile/components/AccountSelection.tsx
  apps/mobile/components/PinNumberModal.tsx
  apps/mobile/package.json
  apps/mobile/public/imgs/friends/agreeWibee.png
  packages/apis/src/bankingService.ts
  packages/ui/src/keyboard.tsx
  pnpm-lock.yaml
Labels: ♻️ refactor, ✨ feature

#131 [refactor/TK-236]: 알림창 및 정산 퍼블리싱 수정
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/travel/[id]/agreement/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/app/travel/[id]/settlement/pending/page.module.css
  apps/mobile/app/travel/[id]/settlement/pending/page.tsx
  apps/mobile/public/imgs/settlement/angryWibee.png
  apps/mobile/public/imgs/settlement/sadWibee.png
  packages/apis/src/notificationService.ts
  packages/ui/package.json
  packages/ui/src/notification-skeleton.module.css
  packages/ui/src/notification-skeleton.tsx
Labels: ♻️ refactor

#137 [Feat/TK-245] 여행 홈 pc 버전, pc 헤더
  apps/pc/app/globals.css
  apps/pc/app/layout.tsx
  apps/pc/app/travel/[id]/invite-code-button.tsx
  apps/pc/app/travel/[id]/page.module.css
  apps/pc/app/travel/[id]/page.tsx
  apps/pc/app/travel/[id]/payments/layout.tsx
  apps/pc/components/Header.module.css
  apps/pc/components/Header.tsx
  apps/pc/middleware.ts
  packages/ui/src/chart.tsx
Labels: ✨ feature

#140 [feat/TK-246]: 공동지출내역 PC 버전
  apps/pc/app/travel/[id]/payments/page.module.css
  apps/pc/app/travel/[id]/payments/page.tsx
  packages/ui/src/animated-button.module.css
  packages/ui/src/payment.tsx
  packages/ui/src/settlement-button.module.css
  packages/ui/src/settlement-button.tsx
Labels: ✨ feature

#130 [Feat/tk 229] -정산 알림 sse 구현
  apps/mobile/app/layout.tsx
  apps/mobile/app/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/RealTimeMsg.module.css
  apps/mobile/components/RealTimeMsg.tsx
  apps/mobile/package.json
  apps/pc/app/layout.tsx
  apps/pc/package.json
  packages/apis/package.json
  packages/apis/src/index.ts
  packages/apis/src/invtieCode.ts
  packages/apis/src/realTimeMsg.ts
  packages/stores/src/index.ts
  packages/stores/src/notificationStore.ts
  packages/types/src/travelServiceType.ts
  packages/ui/src/assets/title/isMsg.png
  packages/ui/src/title.tsx
  pnpm-lock.yaml
Labels: ✨ feature

#133 Feat/tk 239 mypage
  apps/mobile/app/mypage/page.module.css
  apps/mobile/app/mypage/page.tsx
  packages/apis/src/authService.ts
  packages/exception/src/CustomException.ts
  packages/types/src/authType.ts
  packages/ui/src/manual-shared-payment-form.tsx
Labels: ✨ feature

#145 [fix/TK-212]:타이틀 고정, 폰트 설정 추가
  apps/mobile/app/global.css
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/components/TravelForm.module.css
  apps/pc/app/layout.tsx
  apps/pc/app/page.tsx
  apps/pc/components/RealTimeMsg.module.css
  apps/pc/components/RealTimeMsg.tsx
  packages/styles/global.css
  packages/ui/src/title.module.css
Labels: ♻️ refactor

#148 [fix/TK-212]:초대 코드 수정
  apps/mobile/components/InviteCodeModal.tsx
Labels: ✨ feature

#138 [Feat/TK-242] 정산 및 알림 pc 버전 구현 및 퍼블리싱 수정
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/settlement/canceled/page.module.css
  apps/mobile/app/travel/[id]/settlement/canceled/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/app/travel/[id]/settlement/pending/page.tsx
  apps/mobile/components/ModalWrapper.tsx
  apps/mobile/components/OtherExpenseDetails.tsx
  apps/mobile/public/imgs/settlement/cancelWibee.png
  apps/pc/app/notification/page.module.css
  apps/pc/app/notification/page.tsx
  apps/pc/app/travel/[id]/agreement/completed/page.module.css
  apps/pc/app/travel/[id]/agreement/completed/page.tsx
  apps/pc/app/travel/[id]/agreement/page.module.css
  apps/pc/app/travel/[id]/agreement/page.tsx
  apps/pc/app/travel/[id]/settlement/canceled/page.module.css
  apps/pc/app/travel/[id]/settlement/canceled/page.tsx
  apps/pc/app/travel/[id]/settlement/page.module.css
  apps/pc/app/travel/[id]/settlement/page.tsx
  apps/pc/app/travel/[id]/settlement/pending/page.module.css
  apps/pc/app/travel/[id]/settlement/pending/page.tsx
  apps/pc/components/ModalWrapper.tsx
  apps/pc/components/OtherExpenseDetails.tsx
  apps/pc/public/imgs/settlement/angryWibee.png
  apps/pc/public/imgs/settlement/cancelWibee.png
  apps/pc/public/imgs/settlement/sadWibee.png
  packages/ui/src/button.module.css
  packages/ui/src/notification-skeleton.module.css
  packages/ui/src/notification-skeleton.tsx
  packages/ui/src/title.tsx
Labels: ✨ feature

#155 hotfix: 프로필이미지 버그 수정
  apps/mobile/app/travel/[id]/page.tsx
  apps/pc/app/travel/[id]/page.tsx
  packages/ui/src/friend-image.module.css
  packages/ui/src/friend-image.tsx
  packages/ui/src/payment.tsx
Labels: 🚨 hotfix

#154 [fix/TK-212]:버튼 로딩 표시 추가
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/components/TravelForm.tsx
Labels: 🚨 hotfix, ✨ feature

#158 [fix/TK-212]:초대 코드 공유 수정
  apps/mobile/components/InviteCodeModal.tsx
Labels: ♻️ refactor

#161 hotfix: 공동결제내역 코드 안정성 높이기
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/[id]/payments/page.tsx
  packages/ui/src/payment-list.tsx
Labels: ♻️ refactor, 🚨 hotfix

#141 Feat/tk 244 pc 버전 생성
  apps/pc/app/mypage/page.module.css
  apps/pc/app/mypage/page.tsx
  apps/pc/app/travel/[id]/honey-capsule/page.module.css
  apps/pc/app/travel/[id]/honey-capsule/page.tsx
  apps/pc/app/travel/[id]/manual/page.tsx
  apps/pc/app/travel/[id]/wibee-card/page.module.css
  apps/pc/app/travel/[id]/wibee-card/page.tsx
  packages/ui/src/manual-shared-payment-form.module.css
  packages/ui/src/manual-shared-payment-form.tsx
  pnpm-lock.yaml
Labels: ✨ feature

#143 [Feat/tk - 235] 여행 pc 버전 퍼블리싱
  apps/mobile/components/TravelForm.module.css
  apps/pc/app/page.module.css
  apps/pc/app/page.tsx
  apps/pc/app/travel/[id]/form/page.tsx
  apps/pc/app/travel/form/page.tsx
  apps/pc/app/travel/page.module.css
  apps/pc/app/travel/page.tsx
  apps/pc/components/TravelForm.module.css
  apps/pc/components/TravelForm.tsx
  apps/pc/next.config.mjs
  packages/apis/src/travelService.ts
Labels: ✨ feature

#159 [Feat/TK-242] 세부 지출 내역 퍼블리싱 수정
  apps/mobile/app/travel/[id]/settlement/page.module.css
Labels: ♻️ refactor

#149 Feat/tk 225 관리자 페이지 화면 구현
  apps/admin/app/favicon.ico
  apps/admin/app/login-logs/page.module.css
  apps/admin/app/login-logs/page.tsx
  apps/admin/app/page.module.css
  apps/admin/app/page.tsx
  apps/admin/app/travel-management/page.module.css
  apps/admin/app/travel-management/page.tsx
  apps/admin/app/user-management/page.module.css
  apps/admin/app/user-management/page.tsx
  apps/admin/components/Header.tsx
  apps/admin/components/Sidebar.tsx
  packages/apis/src/adminService.ts
  packages/apis/src/index.ts
  packages/types/src/adminType.ts
  packages/types/src/index.ts
Labels: ✨ feature

#163 hotfix: 공동지출내역 suspense 제거 등
  apps/admin/app/page.module.css
  apps/mobile/app/actions/authActions.ts
  apps/mobile/app/travel/[id]/payments/page.tsx
  apps/mobile/public/not_select.png
  apps/mobile/public/select.png
  packages/ui/src/payment-list.tsx
  packages/ui/src/payment.tsx
Labels: ♻️ refactor

#162 Feat/tk 255 로그아웃 및 에러 수정
  apps/mobile/app/actions/authActions.ts
  apps/mobile/app/mypage/page.tsx
  apps/mobile/app/travel/[id]/manual/page.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/[id]/wibee-card/page.module.css
  apps/mobile/app/travel/[id]/wibee-card/page.tsx
  apps/pc/app/travel/[id]/manual/page.tsx
  apps/pc/app/travel/[id]/page.tsx
  apps/pc/app/travel/[id]/wibee-card/page.module.css
  apps/pc/app/travel/[id]/wibee-card/page.tsx
  packages/auth-config/src/index.ts
  packages/ui/src/manual-shared-payment-form.tsx
Labels: 🐞bug, ♻️ refactor, ✨ feature

#164 [fix/TK-212]:초대 코드 복사
  apps/admin/app/page.module.css
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/components/RealTimeMsg.tsx
  apps/mobile/components/TravelForm.tsx
Labels: ♻️ refactor

#165 [Feat/TK-242] 알림창 퍼블리싱 수정
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/settlement/canceled/page.tsx
  apps/mobile/app/travel/[id]/settlement/pending/page.tsx
Labels: ♻️ refactor

#167 Feat/tk 212 여행 생성 모달 수정
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/TravelForm.tsx
  apps/mobile/next.config.mjs
Labels: ♻️ refactor

#168 [fix/TK-212]:퍼블리싱 수정
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/public/copy.png
Labels: ♻️ refactor

#170 [fix/TK-212]:초대코드 퍼블리싱 수정
  apps/mobile/app/global.css
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/InviteCodeModal.tsx
  apps/mobile/package.json
  apps/mobile/public/imgs/travelform/share.png
  packages/apis/src/invtieCode.ts
  pnpm-lock.yaml
Labels: ♻️ refactor

#172 feat/TK-212 : 여행 리스트 이미지 변경
  apps/mobile/public/imgs/travelselect/travel_exam.png
Labels: ♻️ refactor

#169 Feat/tk 257 뱅킹 배포 문제 수정, 퍼블리싱 수정
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/transfer/detail/page.module.css
  apps/mobile/app/banking/[id]/transfer/detail/page.tsx
  apps/pc/app/banking/[id]/deposit/page.tsx
  apps/pc/app/banking/[id]/transfer/detail/page.module.css
  apps/pc/app/banking/[id]/transfer/detail/page.tsx
  apps/pc/app/banking/[id]/transfer/page.module.css
  apps/pc/app/banking/page.tsx
  apps/pc/app/travel/[id]/page.module.css
  apps/pc/app/travel/[id]/page.tsx
  apps/pc/public/not_select.png
  apps/pc/public/select.png
  packages/hooks/package.json
  packages/hooks/src/useIsPC.ts
  packages/ui/src/keyboard.module.css
  packages/ui/src/payment.module.css
  packages/ui/src/payment.tsx
  packages/utils/src/numberToKorean.ts
Labels: 🐞bug, ♻️ refactor

#174 Hotfix: payment 관련 fix
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/transfer/detail/page.tsx
  apps/mobile/app/travel/[id]/manual/page.tsx
  apps/mobile/app/travel/[id]/payments/layout.tsx
  apps/mobile/app/travel/[id]/payments/page.module.css
  apps/mobile/app/travel/[id]/wibee-card/page.tsx
  apps/mobile/components/LoginForm.tsx
  apps/pc/app/travel/[id]/manual/page.tsx
  apps/pc/app/travel/[id]/payments/layout.tsx
  apps/pc/app/travel/[id]/wibee-card/page.tsx
  packages/ui/src/item-group.module.css
  packages/ui/src/item-group.tsx
  packages/ui/src/payment-list.module.css
  packages/ui/src/payment-skeleton.module.css
  packages/ui/src/settlement-button.tsx
Labels: 🐞bug, 🚨 hotfix

#173 [Feat/TK-242] 퍼블리싱 수정
  apps/mobile/app/travel/[id]/agreement/completed/page.module.css
  apps/mobile/app/travel/[id]/settlement/canceled/page.module.css
  apps/mobile/app/travel/[id]/settlement/pending/page.module.css
Labels: ♻️ refactor

#175 Feat/tk 263 종합적인 에러 수정
  apps/mobile/app/travel/[id]/manual/page.module.css
  apps/mobile/app/travel/[id]/manual/page.tsx
  apps/pc/app/travel/[id]/manual/page.module.css
  apps/pc/app/travel/[id]/manual/page.tsx
  packages/apis/src/sharedPaymentsService.ts
  packages/types/src/sharedPaymentsType.ts
  packages/ui/package.json
  packages/ui/src/manual-shared-payment-form.module.css
  packages/ui/src/manual-shared-payment-form.tsx
  packages/ui/src/modal.tsx
  packages/ui/src/record-modal-skeleton.module.css
  packages/ui/src/record-modal-skeleton.tsx
  packages/ui/src/record-modal.tsx
Labels: 🐞bug, 🚨 hotfix

#176 fix: pc 스타일 버그 수정, 정산 route 추가
  apps/pc/app/travel/[id]/payments/layout.tsx
  apps/pc/app/travel/[id]/payments/page.module.css
  packages/ui/src/settlement-button.tsx
Labels: 🐞bug, ✨ feature

#178 [Feat/TK-242] 알림창 퍼블리싱 수정
  apps/mobile/app/notification/page.module.css
  apps/mobile/app/notification/page.tsx
  apps/pc/app/notification/page.module.css
  apps/pc/app/notification/page.tsx
Labels: ♻️ refactor

#179 Feat/tk 212 코드 리팩토링
  apps/mobile/app/not-found.module.css
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/RealTimeMsg.tsx
  apps/mobile/components/TravelForm.module.css
  packages/ui/package.json
  packages/ui/src/travel-list-skeleton.module.css
  packages/ui/src/travel-list-skeleton.tsx
Labels: ♻️ refactor

#184 [fix/TK-212]:카드혜택 퍼블리싱 수정
  apps/mobile/app/page.module.css
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/components/MobileFooter.tsx
  apps/mobile/cypress.config.js
  apps/mobile/cypress/e2e/payment.cy.js
  apps/mobile/cypress/support/command.js
  apps/mobile/cypress/support/e2e.js
  apps/mobile/test/Payment.test.tsx
  apps/mobile/test/test-utils.tsx
Labels: ♻️ refactor

#186 Hotfix: middleware 관련 window 에러 해결, 위비카드 보유 여부에 따라 로그인 라우팅 처리
  apps/mobile/components/LoginForm.tsx
  apps/pc/middleware.ts
Labels: 🐞bug, 🚨 hotfix

#185 [fIX/TK-212]: 멘토님 피드백 리팩토링
  apps/mobile/app/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/public/imgs/travelselect/emptyStateTrip.png
  packages/ui/src/title.tsx
Labels: ♻️ refactor

#190 [Feat/TK-242] 퍼블리싱 수정
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/pc/app/travel/[id]/settlement/page.module.css
Labels: ♻️ refactor

#194 Feat/tk 212 : 에러 수정
  apps/mobile/app/travel/[id]/page.tsx
  packages/stores/src/notificationStore.ts
  packages/ui/src/title.tsx
  packages/ui/src/travel-list-skeleton.module.css
Labels: 🚨 hotfix

#193 Feat/tk 263 종합적인 에러 수정
  apps/mobile/app/mypage/page.tsx
  apps/mobile/app/travel/[id]/wibee-card/page.module.css
  apps/mobile/app/travel/[id]/wibee-card/page.tsx
  packages/types/src/authType.ts
  packages/ui/package.json
  packages/ui/src/honey-capsule.module.css
  packages/ui/src/honey-capsule.tsx
  packages/ui/src/item.tsx
  packages/ui/src/my-page-skeleton.module.css
  packages/ui/src/my-page-skeleton.tsx
  packages/ui/src/payment.tsx
  packages/ui/src/wibee-card-payment.module.css
Labels: 🐞bug, 🚨 hotfix, ✨ feature

#195 [refactor/TK-242]: 지출 상세 내역 퍼블리싱 수정
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/app/travel/[id]/settlement/page.tsx
  apps/mobile/components/OtherExpenseDetails.tsx
Labels: ♻️ refactor

#198 [Feat/TK-242] 퍼블리싱 수정
  apps/mobile/app/travel/[id]/agreement/completed/page.tsx
  apps/mobile/app/travel/[id]/agreement/page.tsx
  apps/mobile/app/travel/[id]/settlement/canceled/page.tsx
  apps/mobile/app/travel/[id]/settlement/page.module.css
  apps/mobile/components/ExpenseDetails.tsx
  apps/mobile/public/imgs/settlement/heartWibee.png
  apps/pc/app/travel/[id]/agreement/page.tsx
  apps/pc/app/travel/[id]/settlement/page.module.css
  apps/pc/app/travel/[id]/settlement/page.tsx
  packages/utils/src/consentItems.ts
Labels: ♻️ refactor

#196 [fix/TK-212]:실시간 알림 초, 배너 광고
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/BannerAds.module.css
  apps/mobile/components/BannerAds.tsx
  apps/mobile/components/MobileFooter.module.css
  apps/mobile/components/RealTimeMsg.tsx
  apps/mobile/public/imgs/travelselect/esim_banner.png
  apps/mobile/public/imgs/travelselect/howhere_banner.png
  apps/mobile/public/imgs/travelselect/kakaoT_banner.png
  apps/mobile/public/imgs/travelselect/triple_com_banner.png
  apps/mobile/public/imgs/travelselect/yanolja_banner.png
  packages/ui/src/title.tsx
  packages/ui/src/travel-list-skeleton.module.css
  pnpm-lock.yaml
Labels: ♻️ refactor

#197 Feat/tk 268 뱅킹 입금 오류 수정
  apps/mobile/app/banking/[id]/deposit/page.module.css
  apps/mobile/app/banking/[id]/deposit/page.tsx
  apps/mobile/app/banking/[id]/page.module.css
  apps/mobile/app/banking/[id]/page.tsx
  apps/mobile/app/banking/[id]/payment/page.module.css
  apps/mobile/app/banking/[id]/payment/page.tsx
  apps/mobile/app/banking/[id]/transfer/detail/page.module.css
  apps/mobile/app/banking/[id]/transfer/detail/page.tsx
  apps/mobile/app/banking/[id]/transfer/page.module.css
  apps/mobile/app/banking/[id]/transfer/page.tsx
  apps/mobile/app/banking/create/page.module.css
  apps/mobile/app/banking/create/page.tsx
  apps/mobile/app/banking/page.module.css
  apps/mobile/app/banking/page.tsx
  apps/mobile/components/AccountSelection.module.css
  apps/mobile/components/AccountSelection.tsx
  apps/pc/app/travel/[id]/payments/page.module.css
  packages/ui/package.json
  packages/ui/src/banking-button.module.css
  packages/ui/src/banking-button.tsx
  packages/utils/src/index.ts
  packages/utils/src/navigationState.ts
Labels: ♻️ refactor

#206 Feat/tk 268 여행 홈 오류 수정
  apps/mobile/app/travel/page.tsx
Labels: 🐞bug

#207 [fix/TK-268] : 초대코드 모달에 서스펜스 적용
  apps/mobile/components/InviteCodeModal.tsx
Labels: 🐞bug

#204 [Feat/tk 212] - 여행 리스트에 맞는 이미지 추가
  apps/mobile/.eslintignore
  apps/mobile/app/travel/[id]/invite-code-button.tsx
  apps/mobile/app/travel/page.module.css
  apps/mobile/app/travel/page.tsx
  apps/mobile/components/BannerAds.tsx
  apps/mobile/components/TravelForm.tsx
  apps/mobile/public/imgs/countries/AR.jpg
  apps/mobile/public/imgs/countries/AT.jpg
  apps/mobile/public/imgs/countries/AU.jpg
  apps/mobile/public/imgs/countries/BR.jpg
  apps/mobile/public/imgs/countries/CA.jpg
  apps/mobile/public/imgs/countries/CH.JPG
  apps/mobile/public/imgs/countries/CL.jpg
  apps/mobile/public/imgs/countries/CN.jpg
  apps/mobile/public/imgs/countries/DE.jpg
  apps/mobile/public/imgs/countries/FR.jpg
  apps/mobile/public/imgs/countries/GR.jpg
  apps/mobile/public/imgs/countries/HK.jpg
  apps/mobile/public/imgs/countries/ID.jpg
  apps/mobile/public/imgs/countries/IN.jpg
  apps/mobile/public/imgs/countries/IT.jpg
  apps/mobile/public/imgs/countries/JP.jpg
  apps/mobile/public/imgs/countries/MX.jpg
  apps/mobile/public/imgs/countries/NL.jpg
  apps/mobile/public/imgs/countries/NZ.jpg
  apps/mobile/public/imgs/countries/SE.jpg
  apps/mobile/public/imgs/countries/US.jpg
  apps/mobile/public/imgs/countries/VN.jpg
  apps/mobile/public/imgs/countries/jeju.png
  apps/mobile/public/imgs/travelselect/jeju.png
  apps/pc/app/travel/form/page.tsx
  apps/pc/components/TravelForm.tsx
  packages/types/src/index.ts
  packages/types/src/travelService.ts
  packages/types/src/travelServiceType.ts
  packages/ui/src/travel-list-skeleton.module.css
  packages/utils/src/consentItems.ts
  pnpm-lock.yaml
Labels: ♻️ refactor

#209 [refactor/TK-242] 알림창 퍼블리싱 수정
  apps/mobile/app/notification/page.module.css
Labels: ♻️ refactor

#210 [fix/TK-212]:애니메이션 추가
  apps/mobile/app/page.module.css
  apps/mobile/app/page.tsx
  apps/mobile/public/imgs/countries/EG.jpg
  apps/mobile/public/imgs/countries/GB.jpg
  apps/mobile/public/imgs/countries/PH.jpg
  apps/mobile/public/imgs/countries/SG.jpg
Labels: ♻️ refactor

#211 Feat/tk 263 리팩토링
  apps/mobile/app/travel/[id]/honey-capsule/page.module.css
  apps/mobile/app/travel/[id]/honey-capsule/page.tsx
  apps/mobile/app/travel/[id]/page.module.css
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/components/TravelMainImage.module.css
  apps/mobile/components/TravelMainImage.tsx
  apps/mobile/package.json
  packages/apis/src/travelService.ts
  packages/types/src/honeyCapsuleType.ts
  packages/ui/package.json
  packages/ui/src/honey-capsule-skeleton.module.css
  packages/ui/src/honey-capsule-skeleton.tsx
  packages/ui/src/honey-capsule.module.css
  packages/ui/src/honey-capsule.tsx
  pnpm-lock.yaml
Labels: 🐞bug, 🚨 hotfix, ✨ feature

#212 [fix/TK-212]:계좌 하이픈 추가
  apps/mobile/app/page.tsx
Labels: 🚨 hotfix

#213 [fix/TK-263]: 계좌 번호 형식 변경
  apps/mobile/app/mypage/page.tsx
Labels: 🚨 hotfix

#215 [Feat/tk 271]: 여행 홈 초대코드 null 값 오류 수정
  apps/mobile/components/InviteCodeModal.tsx
Labels: 🐞bug

#216 [fix/TK-212]:로딩 중 추가
  apps/mobile/app/travel/[id]/form/page.module.css
  apps/mobile/app/travel/[id]/form/page.tsx
  apps/mobile/app/travel/[id]/invite-code-button.tsx
  apps/mobile/app/travel/[id]/page.tsx
  apps/mobile/app/travel/form/page.module.css
  apps/mobile/app/travel/form/page.tsx
  apps/mobile/app/travel/page.tsx
  apps/pc/app/travel/page.tsx
  packages/ui/src/assets/title/isMsg.png
  packages/ui/src/title.tsx
Labels: 🚨 hotfix

#218 [fix/TK-263]: 여행 홈 이미지 수정
  apps/mobile/app/travel/page.tsx
Labels: 🚨 hotfix

#220 [fix/TK-212]:스위스 여행 이미지 수정
  apps/mobile/public/imgs/countries/CH.JPG
  apps/pc/app/travel/form/page.tsx
  apps/pc/app/travel/page.tsx
Labels: 🐞bug

#221 [fix/TK-263]: 숫자 input 사파리에서 숫자만 입력되도록 수정
  packages/ui/src/manual-shared-payment-form.tsx
Labels: 🚨 hotfix

#222 [fix/TK-212]:위비카드 발급시 카드 연결여부 즉시 업데이트
  apps/mobile/app/page.tsx
Labels: 🚨 hotfix

#223 [fix/TK-212]:로그 삭제
  apps/mobile/app/travel/page.tsx
  packages/ui/src/assets/title/isMsg.png
  packages/ui/src/title.tsx
Labels: ♻️ refactor

#227 hotfix: 무한스크롤 버그 해결
  apps/mobile/app/travel/[id]/manual/page.tsx
  apps/pc/app/travel/[id]/manual/page.tsx
  packages/apis/src/sharedPaymentsService.ts
  packages/ui/src/payment-list.module.css
  packages/ui/src/payment-list.tsx
Labels: 🐞bug, 🚨 hotfix

#230 Feat/tk 263 종합적인 에러 수정
  apps/mobile/app/travel/[id]/honey-capsule/page.tsx
  packages/ui/src/honey-capsule.module.css
  packages/ui/src/honey-capsule.tsx
Labels: 🚨 hotfix

#231 [fix/TK-212]:알림 페이지에서 알림 배지 비활성화
  apps/mobile/app/travel/[id]/form/page.tsx
  packages/ui/src/title.tsx
Labels: 🐞bug

#233 [fix/TK-212]:여행 이미지 추가
  apps/mobile/public/imgs/countries/AE.jpg
  apps/mobile/public/imgs/countries/BH.jpg
  apps/mobile/public/imgs/countries/DK.jpg
  apps/mobile/public/imgs/countries/JO.jpg
  apps/mobile/public/imgs/countries/NO.jpg
  apps/mobile/public/imgs/countries/OM.jpg
  apps/mobile/public/imgs/countries/PE.jpg
  apps/mobile/public/imgs/countries/PK.jpg
  apps/mobile/public/imgs/countries/PT.jpg
  apps/mobile/public/imgs/countries/SA.jpg
  apps/mobile/public/imgs/countries/TR.jpg
  apps/mobile/public/imgs/countries/TW.jpg
  apps/mobile/public/imgs/countries/ZA.jpg
Labels: 🚨 hotfix
